// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AlzaSyDm-LnWxMTncU4nvMhdGFyT0Qh2SSjwgIg',
    appId: '1:989890578847:web:8881ef33c1a27c2b7af95b',
    messagingSenderId: '989890578847',
    projectId: 'signin-example-b56ee',
    authDomain: 'vku.udn.vn',
    storageBucket: 'flutterlogin-d7b39.appspot.com',
    measurementId: 'G-Y1ZSXJ386B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AlzaSyDm-LnWxMTncU4nvMhdGFyT0Qh2SSjwgIg',
    appId: '1:989890578847:android:314b30397930f6467af95b',
    messagingSenderId: '989890578847',
    projectId: 'signin-example-b56ee',
    storageBucket: 'flutterlogin-d7b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubN61v-0qiHVFFZ5ZfxPk1epjiPl2v-U',
    appId: '1:1069215963842:ios:89705dd6c6403b6d7af95b',
    messagingSenderId: '1069215963842',
    projectId: 'flutterlogin-d7b39',
    storageBucket: 'flutterlogin-d7b39.appspot.com',
    iosBundleId: 'com.example.googleSignIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAubN61v-0qiHVFFZ5ZfxPk1epjiPl2v-U',
    appId: '1:1069215963842:ios:89705dd6c6403b6d7af95b',
    messagingSenderId: '1069215963842',
    projectId: 'flutterlogin-d7b39',
    storageBucket: 'flutterlogin-d7b39.appspot.com',
    iosBundleId: 'com.example.googleSignIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVr7C0iGiUnJ9s4cgF8o4B0IoncV9z94',
    appId: '1:1069215963842:web:314b30397930f6467af95b',
    messagingSenderId: '1069215963842',
    projectId: 'flutterlogin-d7b39',
    authDomain: 'flutterlogin-d7b39.firebaseapp.com',
    storageBucket: 'flutterlogin-d7b39.appspot.com',
    measurementId: 'G-WZJ2XTPRPX',
  );
}
